runtime: go120

default_expiration: "7d"

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 0.030s
  max_instances: 4

handlers:

# Keep these static file handlers in sync with main.go.
# They're here for improved latency across global regions.
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  secure: always
- url: /content/img
  static_dir: content/img
  secure: always
- url: /static
  static_dir: static
  secure: always

# This is here to redirect all HTTP traffic to an HTTPS URL
# with the same path.
- url: /.*
  script: auto
  secure: always
